language: java
sudo: required
dist: trusty
jdk:
- oraclejdk8
env:
  matrix:
  - TERM=dumb
  global:
  - GRADLE_OPTS="-Xms128m"
  - MALLOC_ARENA_MAX=2
  - secure: CuwlExvbWSRXHB637HlLgP7js+vpiDRbD2kA6QuC/GEi7WuDDkvzqZel/7Sf3bQBAi29LjFCUn7004pfhsrKWZjyEOc2P3abKkWjbIle4t8OuhR7mEGurWmdU4OXxPXU0jZYHHwnu/AUvM/YL9epYtFeOLu+MxIXaf4mJe5IoXM=
  - secure: AXRGnJN4mRaQZ6L7iP63wFKXAM54VANhH4Q2XaQmcXMV+G4Aw66cvFsohg+mlGYYPb8FsGjax0LQrNCbUB4hCC9463qk+e+tfr1dt8ueaycMw9VP4eOA31/RWdvIYSZhKNro35IFDAwMD0jA5TVJFFiYwm3vyTiz/lPVqbVdwTk=
before_install:
- chmod +x gradlew
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END
  CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
before_script:
- sudo service bootlogd stop || true
- sudo service elasticsearch stop || true
- sudo service memcached stop || true
- sudo service mongodb stop || true
- sudo service mysql stop || true
- sudo service neo4j stop || true
- sudo service postgresql stop || true
- sudo service rsync stop || true
- sudo service x11-common stop || true
script:
- free -m && ./gradlew test
after_success:
- "./gradlew jacocoRootReport coveralls"
addons:
  coverity_scan:
    project:
      name: CalebFenton/simplify
      description: Build submitted via Travis CI
    notification_email: calebjfenton@gmail.com
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew build"
    branch_pattern: coverity_scan
