language: java
sudo: required
dist: trusty
jdk:
- oraclejdk8
env:
  matrix:
  - TERM=dumb
  global:
  - GRADLE_OPTS="-Xms128m"
  - MALLOC_ARENA_MAX=2
  - secure: gGxMyKQEwdQP3Ypglo8l6ztHNBNFtO3LCRE9Q5PZVKSYx3Uu7X1mjtJLFxjuUrqZCRI5fhL7GFqT4nLfB594jNSIFy2Z/nTtbIi9MsCaCFD2805ZyWRPXS+E32CB3YneEzfk2aTPIJtsJpQ+8qS7eESpy6jRKxFiaFzb+KPCGNk=
  - secure: g6OMSY52UvQv/Hq2rZ/Qp0+H0IscMVIebJVlNAWiJm13lzwhy8fQFkBvFDLLJcx9foD8LXkvz/QFAwTxhcUwPEFk0Ac4X3QXCzsCirB+KWyZTSGi92YbJG6J5iYSIPZAoTwzdiycApY/z1uMNBNgvmDK6RZY/zgme37MrI9th18=
before_install:
- chmod +x gradlew
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END
  CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
before_script:
- sudo service bootlogd stop || true
- sudo service elasticsearch stop || true
- sudo service memcached stop || true
- sudo service mongodb stop || true
- sudo service mysql stop || true
- sudo service neo4j stop || true
- sudo service postgresql stop || true
- sudo service rsync stop || true
- sudo service x11-common stop || true
script:
- free -m && ./gradlew test
after_success:
- "./gradlew jacocoRootReport coveralls"
addons:
  coverity_scan:
    project:
      name: CalebFenton/simplify
      description: Build submitted via Travis CI
    notification_email: calebjfenton@gmail.com
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew build"
    branch_pattern: coverity_scan
