language: java
jdk:
    - oraclejdk8
    - oraclejdk7

env:
    - TERM=dumb

before_install:
    - chmod +x gradlew

script:
    - ./gradlew clean test

after_success:
    - ./gradlew jacocoTestReport coveralls

sudo: false

cache:
    directories:
        - $HOME/.gradle
